remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Les Temps De Carter]
description: [Les Temps De Carter is a news site that aims to give editorials and opinions about the latest topics]
show_downloads: [false]
github:
  zip_url: [false]
  another_url: [false]
