remote_theme: pages-themes/cayman@v0.2.0
title: [𝔏𝔢𝔰 𝔱𝔢𝔪𝔭𝔰 𝔡𝔢 ℭ𝔞𝔯𝔱𝔢𝔯]
description: [𝔏𝔢𝔰 𝔱𝔢𝔪𝔭𝔰 𝔡𝔢 ℭ𝔞𝔯𝔱𝔢𝔯 is a platform that hopes to post oppinions about current politics plus just fun things.]
show_downloads: ["false"]
